## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
before_script: 
    - wget -O - "http://download.sr-support.com/software/dists/SRResearch/SRResearch_key" | sudo apt-key add -
    - echo "deb http://download.sr-support.com/software SRResearch main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install eyelink-display-software -y
## uncomment the following lines to override the default test script
#script:
after_success:
  # push coverage results to Coveralls
  - julia -e 'using Pkg;cd(Pkg.dir("Eyelink")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'using Pkg;cd(Pkg.dir("Eyelink")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
